server:
  port: "8080"

auth-service:
  address: "auth-service:50051"

product-service:
  address: "product-service:50052"

order-service:
  address: "order-service:50053"

cart-service:
  address: "cart-service:50054"

payment-service:
  address: "payment-service:50055"

review-service:
  address: "review-service:50056"

inventory-service:
  address: "inventory-service:50057"
