server:
  port: "8080"

auth_service:
  address: "localhost:50051"   # or use Docker service name if using docker-compose

product_service:
  address: "localhost:50052"
  
# You can add other microservice endpoints similarly:
 order_service:
   address: "localhost:50053"

 cart_service:
   address: "localhost:50054"

 payment_service:
   address: "localhost:50055"

 review_service:
   address: "localhost:50056"
   
 inventory_service:
   address: "localhost:50057"
