FROM golang:1.24-bullseye AS builder
ENV CGO_ENABLED=1
RUN apt-get update && apt-get install -y \
    git \
    librdkafka-dev \
    pkg-config \
    build-essential

WORKDIR /app
COPY go.mod go.sum ./
RUN sed -i '/replace.*message-broker/d' go.mod && \
    go mod tidy && \
    go get github.com/confluentinc/confluent-kafka-go/v2@latest && \
    go get github.com/geoo115/E-commerceMicroservices/message-broker@latest && \
    go mod download

COPY . .
RUN go build -o order-service .

FROM debian:bullseye-slim
WORKDIR /root/
COPY --from=builder /app/order-service .
EXPOSE 50053
CMD ["./order-service"]