# Build Stage
FROM golang:1.23.6-alpine AS builder

RUN apk update && apk add --no-cache git

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

# Corrected COPY path
COPY message-broker ./message-broker
COPY order-service ./order-service

# Build from the order-service directory
RUN go build -o order-service ./order-service

# Final Stage
FROM alpine:3.20
WORKDIR /root/
COPY --from=builder /app/order-service .
EXPOSE 50053
CMD ["./order-service"]